name: mlflow-basic-auth
channels:
  - conda-forge
dependencies:
  - alembic=1.13.1
  - anyio=4.2.0
  - aws-c-auth=0.7.8
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.10
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.15
  - aws-c-io=0.13.36
  - aws-c-mqtt=0.10.0
  - aws-c-s3=0.4.5
  - aws-c-sdkutils=0.1.13
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.25.0
  - aws-sdk-cpp=1.11.210
  - bcrypt=4.1.2
  - blinker=1.7.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.24.0
  - ca-certificates=2023.11.17
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - configparser=5.3.0
  - contourpy=1.2.0
  - cryptography=41.0.7
  - cycler=0.12.1
  - databricks-cli=0.18.0
  - docker-py=6.1.3
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - flask=3.0.0
  - fonttools=4.47.0
  - freetype=2.12.1
  - gflags=2.2.2
  - gitdb=4.0.11
  - gitpython=3.1.40
  - glog=0.6.0
  - greenlet=3.0.3
  - gunicorn=21.2.0
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.2
  - httpx=0.26.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.0.1
  - importlib_resources=6.1.1
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - joblib=1.3.2
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20230802.1
  - libarrow=14.0.2
  - libarrow-acero=14.0.2
  - libarrow-dataset=14.0.2
  - libarrow-flight=14.0.2
  - libarrow-flight-sql=14.0.2
  - libarrow-gandiva=14.0.2
  - libarrow-substrait=14.0.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.58.0
  - libopenblas=0.3.25
  - libparquet=14.0.2
  - libpng=1.6.39
  - libprotobuf=4.24.4
  - libre2-11=2023.06.02
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.3
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - mako=1.3.0
  - markdown=3.5.1
  - markupsafe=2.1.3
  - matplotlib-base=3.8.2
  - mlflow=2.9.2
  - munkres=1.1.4
  - ncurses=6.4
  - numpy=1.26.2
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=3.2.0
  - orc=1.9.2
  - packaging=23.2
  - pandas=2.1.4
  - paramiko=3.4.0
  - pillow=10.1.0
  - pip=23.3.2
  - prometheus_client=0.19.0
  - prometheus_flask_exporter=0.23.0
  - protobuf=4.24.4
  - pthread-stubs=0.4
  - pyarrow=14.0.2
  - pycparser=2.21
  - pyjwt=2.8.0
  - pynacl=1.5.0
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3.post1
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.1
  - querystring_parser=1.2.4
  - re2=2023.06.02
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - setuptools=68.2.2
  - six=1.16.0
  - smmap=5.0.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - sqlalchemy=2.0.23
  - sqlparse=0.4.4
  - tabulate=0.9.0
  - threadpoolctl=3.2.0
  - tk=8.6.13
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2023d
  - unicodedata2=15.1.0
  - urllib3=2.1.0
  - websocket-client=1.7.0
  - werkzeug=3.0.1
  - wheel=0.42.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.17.0
  - zstd=1.5.5
